### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ermshiperete**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/testbloom/8)

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-TestBloom-Wrapper-debug/6/
Build Successful

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-TestBloom-Wrapper-debug/7/
Build Successful

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-TestBloom-Wrapper-debug/8/
Build Successful

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-TestBloom-Wrapper-debug/9/
Build Successful

**Pull request closed without merging**
